okta:
  oauth2:
    issuer: {issuer}
    client-Id: {client-Id}
    client-Secret: {client-Secret}
    redirect-uri: /authorization-code/callback

server:
  port : 8081

spring:
  thymeleaf:
    cache: false