okta:
  oauth2:
    issuer: ${issuer}
    client-Id: ${clientId}
    client-Secret: ${clientSecret}
    redirect-uri: /authorization-code/callback

server:
  port : 8080

spring:
  thymeleaf:
    cache: false
